"""Add translation jobs table

Revision ID: 3f8e9d2a1b4c
Revises: 2e4fcd375bf7
Create Date: 2025-01-11 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f8e9d2a1b4c'
down_revision: Union[str, None] = '2e4fcd375bf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translation_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('youtube_url', sa.String(), nullable=False),
    sa.Column('source_language', sa.String(), nullable=False),
    sa.Column('target_language', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('video_path', sa.String(), nullable=True),
    sa.Column('audio_path', sa.String(), nullable=True),
    sa.Column('chunks_data', sa.JSON(), nullable=True),
    sa.Column('final_video_path', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translation_jobs_id'), 'translation_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_translation_jobs_job_id'), 'translation_jobs', ['job_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translation_jobs_job_id'), table_name='translation_jobs')
    op.drop_index(op.f('ix_translation_jobs_id'), table_name='translation_jobs')
    op.drop_table('translation_jobs')
    # ### end Alembic commands ###